### ISSUE TITLE
Compress back LIUM_SpkDiarization-4.7(given in voiceid-0.2/share) into jar after extracting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [taf2/voiceid#14]
```
If I extract the folder LIUM_SpkDiarization-4.7.jar given in share folder and 
then compress it back using export from eclipse, install the setup again, the 
code stops working and gives the following error :

OSError: Subprocess <subprocess.Popen object at 0x7f63576588d0> closed 
unexpectedly [java -Xmx2048m -jar 
/usr/local/share/voiceid/LIUM_SpkDiarization-4.7.jar 
fr.lium.spkDiarization.system.Diarization --fInputMask=%s.wav 
--sOutputMask=%s.seg --doCEClustering s27]


Using voiceid-0.2 in Ubuntu-12.04

Code runs successfully but once extract LIUM_SpkDiarization-4.7.jar and 
compress back again into .jar , it stops working.Can you please help on what 
method to use for compressing?
```

Original issue reported on code.google.com by `goelanur...@gmail.com` on 3 Jul 2013 at 8:59

**Comment by AhmedHanie** [comment]
Hello,
Please i am facing the same error i guess, and i need to run the application urgently for my graduation project. can you tell me how you fixed it in details if possible . thank you 

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/bin/voiceidplayer", line 1105, in extract_speakers
    self.voiceid.extract_speakers(False, False, 4)
  File "/usr/local/lib/python2.7/dist-packages/voiceid/sr.py", line 991, in extract_speakers
    self.diarization()  # start diarization over your wave file
  File "/usr/local/lib/python2.7/dist-packages/voiceid/sr.py", line 781, in diarization
    str(self._diar_conf[1]))
  File "/usr/local/lib/python2.7/dist-packages/voiceid/fm.py", line 544, in diarization
    + ' --sOutputMask=%s.i.seg ' + filebasename)
  File "/usr/local/lib/python2.7/dist-packages/voiceid/utils.py", line 79, in start_subprocess
    raise err
OSError: Subprocess <subprocess.Popen object at 0x73e1ab30> closed unexpectedly [java -Xmx2048m -classpath /usr/local/share/voiceid/LIUM_SpkDiarization-4.7.jar fr.lium.spkDiarization.programs.MSegInit   --fInputMask=%s.wav --fInputDesc=audio2sphinx,1:1:0:0:0:0,13,0:0:0  --sOutputMask=%s.i.seg /home/pi/Samples/sample-1_]
