### ISSUE TITLE
OSError: Subprocess closed unexpectedly

### ISSUE THREAD

**Issue by AhmedHanie** [taf2/voiceid#37]
please i need to solve this error urgently as i'm using the program as a part of my graduation project  

```
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(self.__args, *self.__kwargs)
File "/usr/local/bin/voiceidplayer", line 1105, in extract_speakers
self.voiceid.extract_speakers(False, False, 4)
File "/usr/local/lib/python2.7/dist-packages/voiceid/sr.py", line 991, in extract_speakers
self.diarization() # start diarization over your wave file
File "/usr/local/lib/python2.7/dist-packages/voiceid/sr.py", line 781, in diarization
str(self.diar_conf[1]))
File "/usr/local/lib/python2.7/dist-packages/voiceid/fm.py", line 544, in diarization
+ ' --sOutputMask=%s.i.seg ' + filebasename)
File "/usr/local/lib/python2.7/dist-packages/voiceid/utils.py", line 79, in start_subprocess
raise err
OSError: Subprocess closed unexpectedly [java -Xmx2048m -classpath /usr/local/share/voiceid/LIUM_SpkDiarization-4.7.jar fr.lium.spkDiarization.programs.MSegInit --fInputMask=%s.wav --fInputDesc=audio2sphinx,1:1:0:0:0:0,13,0:0:0 --sOutputMask=%s.i.seg /home/pi/Samples/sample-1]
```

**Comment by RemiseMichel** [comment]
I have the same problem when i run the command vid -i 2____.wav -u  on ubuntu: 

converting_file
diarization
Traceback (most recent call last):
  File "/usr/local/bin/vid", line 138, in <module>
    thrd_n=multiprocessing.cpu_count() \* 5)
  File "/usr/local/lib/python2.7/dist-packages/voiceid/sr.py", line 991, in extract_speakers
    self.diarization()  # start diarization over your wave file
  File "/usr/local/lib/python2.7/dist-packages/voiceid/sr.py", line 781, in diarization
    str(self._diar_conf[1]))
  File "/usr/local/lib/python2.7/dist-packages/voiceid/fm.py", line 544, in diarization
    + ' --sOutputMask=%s.i.seg ' + filebasename)
  File "/usr/local/lib/python2.7/dist-packages/voiceid/utils.py", line 79, in start_subprocess
    raise err
OSError: Subprocess <subprocess.Popen object at 0x7f2a8b939190> closed unexpectedly [java -Xmx2048m -classpath /usr/local/share/voiceid/LIUM_SpkDiarization-4.7.jar fr.lium.spkDiarization.programs.MSegInit   --fInputMask=%s.wav --fInputDesc=audio2sphinx,1:1:0:0:0:0,13,0:0:0  --sOutputMask=%s.i.seg 2____]

I removed the packages and installed the older package. I checked that I installed the right version by typing dpkg -s sphinxbase-utils. It shows me 0.4.1-0ubuntu1 like it should.
Does someone knows why I still get OSError?

Thank you a lot for your consideration,
Otherend
